s=set()
n=input("enter 1st number:")
s.add(int(n))
n=input("enter 1st number:")
s.add(int(n))
n=input("enter 1st number:")
s.add(int(n))
n=input("enter 1st number:")
s.add(int(n))
n=input("enter 1st number:")
s.add(int(n))
n=input("enter 1st number:")
s.add(int(n))
n=input("enter 1st number:")
s.add(int(n))
n=input("enter 1st number:")
s.add(int(n))

print(s)